### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by ParkWonBin** [ParkWonBin/UIPath_study#5]
### 신규 제작 : 
  - [ ] 커스텀  UI 다이얼로그
  - [ ] 엑셀 열고 엑셀 앱 반환 함수
  - [ ] 엑셀 쓰기(앱,시트명,시작셀,테이블)
  - [ ] 엑셀 읽기(앱,시트명,시작셀)
  - [x] 엑셀 종료 및 kill 함수 [▶ Code](https://github.com/ParkWonBin/UIPath_study/blob/Master/Functions/Fnc_Kill_Process_By_Name.vb)
  - [x] HowTo Readme Updater [▶ Code](https://github.com/ParkWonBin/UIPath_study/blob/Master/Apps/App_Convertion_IE_TO_Edge.vb)
### 기존함수 정리 :
  - [ ] Uipath 과제 분석기 정리
  - [x] 메일 읽고 테이블로 반환 함수 [▶ Code1](https://github.com/ParkWonBin/UIPath_study/blob/Master/Functions/Fnc_MailList_To_DataTable.vb) [▶ Code2](https://github.com/ParkWonBin/UIPath_study/blob/Master/Functions/Fnc_Mail_GetAttr.vb)
  - [x] Ui속성값 모두 써주는 함수 [▶ Code](https://github.com/ParkWonBin/UIPath_study/blob/Master/Functions/Fnc_Bake_UiElementAttar.vb)
  - [ ] Uipath Missing Image 일괄 제거 모듈 제작
### UiPath Util App 만들기
  - [ ] Missing 이미지 전부 지워주는 함수
  - [ ] 과제 분석 & 변환기 제작
  - [ ] Update Readme
  - [ ] Update Function Dependency
  - [ ] Update Custom Functions
  - [ ] Bake_Config
  - [ ] Bake_Emails
  - [ ] Bake_UiElement
### Howto 요령 정리 
- [ ] Howto > Linq.md
- [ ] Howto > String.md
- [ ] Howto > vb.md
- [ ] Howto > Excel.md
- [ ] Howto > ReadMe.config
- [ ] Howto > ReadMe.md
- [ ] Howto > Liblary 생성 및 배포
- [ ] Howto > System 단축키 모음
- [ ] Howto > 변수 이름 규칙
### Issue 생성해서 정리 할 것
  - [ ] Uipath Studio 에러
  - [ ] Uipath Liblary 배포 요령 및 이슈
  - [x] Uipath Selector 이슈
  - [x] File System 관련 이슈

**Comment by ParkWonBin** [comment]
### Edge 버전 고정
1. IE 지원 중단으로 Edge 사용
2. Edge 이전 버전으로 롤백  [▶MS 문서 보기](https://docs.microsoft.com/ko-kr/deployedge/edge-learnmore-rollback#enable-rollback-manually-with-an-msi)
- 주요 부분 ```C:\Users\username\Desktop\test>msiexec /I FileName.msi /qn ALLOWDOWNGRADE=1```
- Edge 버전에 따라 Uipath 셀렉터가 달라지는 경우 존재. RPA 개발 시 특정 버전으로 고정 권장. (가만 두면 자동 업데이트됨)

**Comment by ParkWonBin** [comment]
### Uipath Custom Liblary 수정 시 주의사항 
#### 1. missing이 발생하는 경우는 다음과 같음
  - 1.1. argument의 이름변경, 추가, 삭제, in/out변경 이뤄진 경우
  - 1.2. Liblary 프로젝트 폴더 내 트리구조 변경 및 모듈 경로가 변경된 경우 (모듈 이름 변경 포함)
#### 2 missing이 발생하지 않는 경우
  - 2.1. argument 디폴트값 변경
  - 2.2. argument IsRequire 체크 여부 변경
#### 3. missing 대처방안
  - 3.1. missing 이전 버전 패키지로 원상복구
  - 3.2. missing 된 Liblary 의 argument 내용 백업
  - 3.3. missing 해당 Liblary 삭제 후 패키지 업데이트
  - 3.4. 최신 버전 패키지의 Liblary 에 argument 값 재적용
