### ISSUE TITLE
Window OS & File System참고사항

### ISSUE THREAD

**Issue by ParkWonBin** [ParkWonBin/UIPath_study#6]
### File System Issues
- [x] 운영체제 숨김 파일 관련 [▶ 내용보기](https://github.com/ParkWonBin/UIPath_study/issues/6#issuecomment-1090265925)
   - 빈 폴더에서 ```Syste.IO.Directory.GetFiles(str_Path)``` 에서 못 보던 파일이 등장할 때
   - 빈 폴더에 파일을 업로드 하는데, "이미 존재하는 파일입니다" 경고 문구가 나올 때
- [x]  존재하는 파일 경로가 유효하지 않다고 나올 때  [▶ 내용보기](https://github.com/ParkWonBin/UIPath_study/issues/6#issuecomment-1091045487)
    - File 속성 창에서 복사한 경로를 사용했는데  ```System.IO.File.Exsit(Str_Path)```=False 

### Window OS 
- [x] System32 경로에 존재하지 않는 앱이 실행되는 경우[▶ 내용보기](https://github.com/ParkWonBin/UIPath_study/issues/6#issuecomment-1091057379)

### Tips 
- [x] windows 버튼 안눌릴 때 window App 사용 [▶ 내용보기](https://github.com/ParkWonBin/UIPath_study/issues/6#issuecomment-1091052907)
- [x] 파일 정보 가져오기 [▶ 내용보기](https://github.com/ParkWonBin/UIPath_study/issues/6#issuecomment-1090324959)
- [x] 폴더 내 파일 가져오기 [▶ Code](https://github.com/ParkWonBin/UIPath_study/blob/Master/Functions/Fnc_Get_All_Files.vb)

### ※ Help! 
- [ ] 파일 복제 시 접근 차단 관련  
    - ```System.IO.File.Copy(원본경로,사본경로)``` 사용 시 엑세스 불가 에러가 생길 때가 있습니다. 
    - 로컬PC에서 이슈 발생. chmod [▶ 참고](https://recipes4dev.tistory.com/175) 때문인지, 보안프로그램 때문인지 원인 불명.

**Comment by ParkWonBin** [comment]
## 운영체제 숨김 파일 관련
### 현상
 ``` System.IO.File.Exist("파일경로") ``` = True 가 나오지만, 해당 폴더를 열어보면 폴더가 비어있는 경우
 ``` System.IO.Directory.GetFiles("폴더경로") ``` 에는 존재하는 파일로 나오지만, 해당 폴더에서 보이지 않는 경우

### 원인
```숨김 파일 표시``` = True 로 설정을 해도, 표시되지 않는 파일이 있습니다. 
```보호된 운영체제 파일 숨기기(권장)``` = False 로 설정을 해야만 조회가 가능 파일이 그러한 경우 입니다.

### 대처
####  설정/해제 [▶참고자료](https://forbes.tistory.com/628) 
  - 숨김 설정 : ``` attrib +s +h "절대경로 입력" ```
  - 해제 설정 : ``` attrib -s -h "절대경로 입력" ```

####  조회 방법 [▶참고자료](https://blog.alyac.co.kr/259)
[explorer.exe] 실행 > [보기 tab] 클릭 > [옵션 toolbar] 클릭 > [보기 tab] 클릭
  - ```보호된 운영 체제 파일 숨기기(권장)```=False  선택 
  - ``` 숨김 파일, 폴더 및 드라이브 표시 ```=True 선택

![image](https://user-images.githubusercontent.com/57087624/161981244-f85d747f-aea6-442b-bf2d-231bfd02b662.png)

**Comment by ParkWonBin** [comment]
##  파일 정보 가져오기
파일 정보를 가져오는 방법은 2가지 방법이 있습니다.
1. ```System.IO.File```, ```System.IO.Path```, ```System.IO.Directory``` 등에서 Static 함수 호출
2. ```System.IO.FileInfo```, ```System.IO.DirectoryInfo``` 등에서 객체 생성 후 맴버값으로 정보 추출

(1) Static 함수의 장점은 불필요한 객체를 생성하지 않기 때문에 가볍게 쓰기 좋습니다.
(2) 객체를 생성하는 방법의 장점은 File, Path, Directory 등에 나눠져 있던 기능을 하나의 객체에서 관리할 수 있습니다.

특정 파일의 속성값을 여러개 호출할 필요가 적을 때는,   
불필요하게 객체를 만들기 보다는 System.IO에서 적절한 Static 함수 찾아 쓰는 것이 좋을 것 같습니다.  

## System.IO 관련
```vb
' 파일 정보 관련 (Static 함수)
System.IO.Directory.Exists(Str_Path)        ' 폴더 존제하면 True
System.IO.File.Exists(Str_Path)             ' 파일 존재하면 True
System.IO.file.GetCreationTime(Str_Path)    ' 파일 최초 생성 시간
System.IO.file.GetLastWriteTime(Str_Path)   ' 파일 최종 수정 시간
System.IO.file.GetLastAccessTime(Str_Path)  ' 파일 최종 접근 시간
System.IO.file.GetAttributes(Str_AttarName) ' 파일 속성 확인
System.IO.Path.GetDirectoryName(Str_Path) : ' 해당 경로의 상위 폴더 경로를 반환한다.
System.IO.Path.GetFileName(Str_Path)        ' 확장자 포함 파일명 ex) "Main.xaml"
System.IO.Path.GetExtension(Str_Path)       ' 확장자 반환 ex) ".xaml"
System.IO.Path.GetFileNameWithoutExtension(Str_Path) ' 확장자 미포함 파일명 ex) "Main"

' 파일 정보 관련 (객체 매소드 사용)
(new System.IO.DirectoryInfo(Str_Path)).Exists    ' 폴더 존재하면 True
(new System.IO.FileInfo(Str_Path)).Exists         ' 파일 존재하면 True
(new System.IO.FileInfo(Str_Path)).CreationTime   ' 파일 최초 생성 시간
(new System.IO.FileInfo(Str_Path)).LastWriteTime  ' 파일 최종 수정 시간
(new System.IO.FileInfo(Str_Path)).LastAccessTime ' 파일 최종 접근 시간
(new System.IO.FileInfo(Str_Path)).Attributes(Str_AttarName) ' 파일 속성 확인
(new System.IO.FileInfo(Str_Path)).DirectoryName  ' 해당 경로의 상위 폴더 경로를 반환한다.
(new System.IO.FileInfo(Str_Path)).Name           ' 확장자 포함 파일명 ex) "Main.xaml"
(new System.IO.FileInfo(Str_Path)).Extension      ' 확장자 반환 ex) ".xaml"
```

#### 그 외 파일/폴더 생성 및 삭제 관련 
```vb
' 경로 입력 관련
System.IO.Path.Combine(A,B,...) ' 경로 합쳐서 반환. 
' A,B,C... 의 마지막 문자에 경로 구분자(\)가 있든 없든 정상적으로 경로 합쳐서 반환하기 떄문에 많이 씁니다.

' 경로 내 검색 관련
System.IO.Directory.GetFiles(Str_Path)       ' 해당 경로에 위치한 파일의 절대경로를 String_Array로 반환한다. 
System.IO.Directory.GetDirectories(Str_Path) ' 해당 경로에 위치한 폴더의 절대경로를 String_Array로 반환한다.
System.IO.Directory.GetFiles(Str_Path,"*",System.IO.SearchOption.AllDirectories) '해당 경로 내 모든 파일

' 파일 작성 및 삭제 관련
System.IO.Directory.CreateDirectory(Str_Path) ' 폴더 생성
System.IO.File.ReadAllText(Str_Path, System.Text.Encoding.UTF8) ' 파일 읽기. Encoding 설정 가능
System.IO.File.WriteAllText(Str_Path, Str_Content, System.Text.Encoding.UTF8) '파일 생성. Encoding 설정 가능
System.IO.File.AppendAllText(Str_Path, Str_Content, System.Text.Encoding.UTF8) '파일 이어서 쓰기. Encoding 설정 가능
System.IO.File.Copy(Str_Sorce,Str_Dest,Bln_overwite) ' 파일 복제. 덮어쓰기 여부 선택
System.IO.File.Delete(Str_Path) ' 파일 삭제
```

## System.Environment 관련
```vb
System.Environment.CurrentDirectory ' 현제 프로젝트 경로 반환
System.Environment.GetEnvironmentVariable(Str_KeyName) ' 환경변수에 저장된 값 반환, key가 없을 경우 "" 반환
System.Environment.SetEnvironmentVariable(Str_KeyName, Str_Value) ' 해당 Key에 value값을 적용한다.
Environment.GetFolderPath(Environment.SpecialFolder.Desktop) ' 해당 PC의 바탕화면
```

**Comment by ParkWonBin** [comment]
## 파일 경로 문자열이 고장날 떄
Code 에디터 상 파일 경로가 제대로 입력되었는데 "유효한 경로 아님 Error"가 발생하는 경우가 있다.
문자의 폭이 0인 특수문자가 있는지 확인할 것.

### 현상 
A : window 탐색기 > 주소창 > 경로
B : window 탐색기 > 파일 속성>보안>개체이름 > 전체 드레그하여 복사
```vb
A = "C:\Users\UserName\Desktop\tmp\test.xlsx" 
B = "‪C:\Users\UserName\Desktop\tmp\test.xlsx" 

System.IO.File.Exists(A) '= True  
System.IO.File.Exists(B) '= False 

A.Length  '= 39
B.Length  '= 40
```
### 대처 
Uipath 입력창에 있는 경로를 VScode에 복사-붙여넣기 하여 확인하면 특수 문자가 명확하게 표시된다.
```vb
A = "C:\Users\UserName\Desktop\tmp\test.xlsx"
B = "[U+202A]C:\Users\UserName\Desktop\tmp\test.xlsx"
```

### 예방 방법 : 
다음과 같은 Linq로 보완로직을 만들어 확인할 수도 있다. 
Ascii Code  63번은  아스키 코드에 등록되지 않은 문자를 의미한다.
Linq로 Ascii Code 63번에 해당하는 문자를 모두 지워주는 코드
```vb
Str_Path = join(Str_Path.where(function(x) asc(x)<>63).Select(function(x) x.ToString).ToArray,"")
```

**Comment by ParkWonBin** [comment]
## [Window 시작] 버튼 안 눌릴 때 window app 사용하기
윈도우 탐색기가 열린다면 시스템 경로 이동하여 수동으로 app 실행이 가능합니다.  

1. 파일 탐색기 열기
2. 경로 이동 : ```C:\Windows\System32```
3. App 찾아서 실행
     - mstsc.exe ' =원격접속 
     - mspaint.exe '=그림판

Window 키가 정상 동작할 때는 실행 창 [Window + R]에 해당 App 이름을 입력하여 진입 가능
```yaml
원격접속 :  [Window + R] > "mstsc" 
그림판   :  [Window + R] > "mspaint"
```

**Comment by ParkWonBin** [comment]
## System32 경로에 존재하지 않는 앱이 실행되는 경우
### [▶ 참고 : 몽키의 IT개발 노트](https://pung77.tistory.com/23) 

| 폴더명 | 경로 위치 | 비고 |
|:---:|---|:---|
System32 | C:\Windows\System32 | 64bit 프로세스는 System 32 을 참조하여 실행된다.
SysWOW64 | C:\Windows\SysWOW64 | 32bit 프로세스는 SysWOW64 을 참조하여 실행된다.

#### [▶ 관련 MS 문서1](https://msdn.microsoft.com/ko-kr/library/windows/desktop/aa384187(v=vs.85).aspx )
Windows는 File System Redirector라는 기능을 지원하여,   
Sytem32 폴더에 접근하여 사용하려 하여도 SysWOW64 폴더로 리다이렉트 시켜 자동으로 SysWOW64 폴더의 내용을 참조한다.   

예를들어 64bit os에서 
32bit 프로세스가  LoadLibrary(C:\windows\System32\Kernel32.dll) 을 호출하여 Kernel32.dll을 로딩하려 하여도 
실제로는 리다이렉트되어 C:\windows\SysWOW64\Kernel32.dll 경로의 Kernel32.dll을 참조한다.

#### [▶ 관련 MS 문서2](https://msdn.microsoft.com/ko-kr/library/windows/desktop/aa365744(v=vs.85).aspx)
32bit 프로세스가 System32 폴더에 접근하고 싶다면 Wow64EnableWow64FsRedirection API를 사용해 리다이렉트 기능을 끄고 강제로 접근하면된다.
