### ISSUE TITLE
MS Edge 자동화 관련 참고사항

### ISSUE THREAD

**Issue by ParkWonBin** [ParkWonBin/UIPath_study#7]
### 버그대처
- [x] Edge 종료 후 서버 인증 토큰 관련 이슈 [▶ 내용보기](https://github.com/ParkWonBin/UIPath_study/issues/7#issuecomment-1107942133)

### 환경 설정
  - [x] Edge 버전 낮추고 고정하기 [▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/7#issuecomment-1090376387)

### 편의 기능
  - [x]  Edge 관련 단축키 [▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/7#issuecomment-1090359947)
  - [x] IE => Edge 변환 tool [▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/7#issuecomment-1090376735)

### 개발 관련
  - [x] Selector ```idx='*'``` 명시 [▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/7#issuecomment-1090374178)
  - [x] Uipath Selector tag 관련 [▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/7#issuecomment-1090375567)  [▶ Uipath 문서 Selector ](https://docs.uipath.com/studio/docs/about-selectors)

**Comment by ParkWonBin** [comment]
## EDGE 관련 단축키 
### [▶ 참고1](https://mainia.tistory.com/4086) [▶ 참고2](https://thelumine.wordpress.com/2015/08/27/microsoft-edge-keyboard-shortcuts/)

|단축키 | 기능 |
|--|--|
| Ctrl+W | 현재 탭 닫기 |
| Ctrl+1~Ctrl+8 | 창의 특정 위치에 있는 탭으로 이동 |
| Ctrl+9 | 창의 마지막 탭으로 이동 |
| Ctrl+0 | 창의 화면 비율 100%로 조정 |
| Ctrl+Shift+T | 마지막으로 닫았던 탭 열기 |
| Ctrl+Tab | 창의 다음 탭으로 이동	|
| Ctrl+Shift+Tab | 창의 이전 탭으로 이동	|
| Ctrl+U | 페이지 소스 보기 |
| Ctrl+Shift+I | 개발자 도구 패널 표시/숨김 |

**Comment by ParkWonBin** [comment]
## 간헐적으로 팝업을 못 잡을 때
최상위 Selector Node를 설정할 때 ``` idx='*' ``` 를 명시하면 갑자기 Element가 Valid 하게 될 때가 있습니다. 
Selector가 모호할 때, 검출된 모든 Element에 대해 탐색하지 않을 때가 있는 것 같아 보입니다. 

```xml
<!-- 가장 앞서 포커스 된 Edge에 대해 동작함 -->
<html app='msedge.exe'/>

<!-- Process에 열려있는 모든 Edge Window를 살펴보나봄 -->
<html app='msedge.exe' idx='*' />
```

**Comment by ParkWonBin** [comment]
## 셀렉터 테그 확인 
### [▶ Uipath 문서 확인](https://docs.uipath.com/studio/docs/about-selectors)
1. \<html>, \<wnd>, \<ctrl> 등 테그 속성을 확인하고, 적절한 값으로 셀렉터 찍기  
2. 팝업에 있는  Text는 name이나 title 속성에 들어있을 확률이 높다.  
3. \<wnd/> 에서 title, aaname 으로 보이는 글자를 넣어본다.  
4. \<ctrl/> 에서 role, name, text 등을 잡아본다.   
5. "app" 속성 명시하고, url로 잡으면 팝업은 웬만해서 잡을 수 있다. 
    - (2022.03.27) UIAutomation 21.4.4 기준

## 팝업 생성 및 셀렉터 잡기
개발자 도구[F12] > Console > 팝업 함수 실행
```JS 
alert("test")
confirm("test")
```
ui explorer로 브라우저 팝업을 잡으려고 하면 Studio가 멈추는 경우가 있습니다.  (Uipath Studio 19.10 버전 기준)
Selector 선택 Element 선택 과정에서 대기 시간이 비정상적으로 긴 경우, 
target > WaitForReady > None 으로 바꿔서 조치가 가능. (무한대기 방지)  

```xml
<!-- Edge 팝업 확인 버튼 클릭 -->
<html app='msedge.exe' url='*' />
<ctrl role='dialog' />
<ctrl role = 'push button' name='확인'/>

<!-- GetText 크롬 팝업 내 텍스트 지정 -->
<html app='chrome.exe' title='*' />
<ctrl role='dialog' />
<ctrl role='text' name='*.*' />

<!-- Edge Alert 텍스트 박스 - GetText -->
<wnd app='msedge.exe' title='*' />
<ctrl role='dialog' />
<ctrl idx='15' role='pane' />

<!-- Edge Alert/Confirm 1번째 버튼 - Click -->
<wnd app='msedge.exe' title='*' />
<ctrl role='dialog' />
<ctrl role='pane' idx='4' />
<ctrl role='push button' idx='1' />
<!-- 해당 UI의 버튼에 써있는 글자는 name 속성으로 - Get Attr -->
<!-- Confirm에서 취소버튼 등 2번째 버튼은 마지막 테그의 idx = '2' 입력 -->
```

**Comment by ParkWonBin** [comment]
## Edge 버전 낮추기 & 고정 하기  
### 버전 낮추기 [▶ MS 문서 보기](https://docs.microsoft.com/ko-kr/deployedge/edge-learnmore-rollback#enable-rollback-manually-with-an-msi)
 - 주요 부분 ```C:\Users\username\Desktop\test>msiexec /I FileName.msi /qn ALLOWDOWNGRADE=1```
 - Edge 버전에 따라 진입이 불가한 업무 시스템 존재. 
 - RPA 개발 시 특정 버전으로 고정 권장. (가만 두면 자동 업데이트됨)

### 버전 고정하기 [▶ 참고](https://devjit.tistory.com/159)
1. 파일 탐색기 열기 (window키+e)
2. C:\Program Files (x86)\Microsoft\EdgeUpdate로 이동 (32비트, C:\Program Files\...)
3. MicrosoftEdgeUpdate.exe 속성으로 들어가서 보안 탭을 클릭 (alt+enter)
4. SYSTEM을 선택한 후, 모든 권한 거부를 체크하고 적용 (* 작업관리자에서 프로세스 사용자가 SYSTEM이므로 해당 권한 거부)

**Comment by ParkWonBin** [comment]
## IE 전환 과제 Edge로 자동 변환 
### App_Convertion_IE_TO_Edge [▶ Code](https://github.com/ParkWonBin/UIPath_study/blob/Master/Apps/App_Convertion_IE_TO_Edge.vb)

- 확인사항
   - UIAutomation  = 21.4.4 버전을 기준으로 셀렉터를 잡았습니다.
   - 특징1 : Selector 내에서 app을 명시
   - 특징2 : 최상위 node는 ```<html app='msedge.exe' url='*{{Str_URL}}*' />``` 노드를 사용합니다.
   - kill Process 와 셀랙터 내 {{변수호출}} 정도 수정
- 주의사항
   - UIAutomation 버전에 따라서 유효한 셀렉터가 다를 수 있습니다. 
   - UIAutomation =19.4 에서 유효한 셀랙터가 21.4에서 찾을 수 없을 때가 있습니다.
   - UIAutomation = 21.4에서 유효한 셀렉터가 19.4에서 찾을 수 없을 때가 있습니다.

```yaml
Dependency :
  - Uipath.Core.UIAutomation=21.4
Remark :
  - 패키지 업데이트는 수동으로 진행하셔야 합니다.(버전 확인 필수)
Target:
  - Open Browser/Attach Browser 의 BrowserType 수정
  - 파일명에 %20이 있는 경우 ' '으로 바꿔줍니다.(Nuget에서 추출한 경우)
  - Selector 속성에 app이 명시되지 않은 경우 msedge로 변경
  - Selector 내에서 변수를 호출하는 경우 {{ }}로 바꾸어줍니다.
    - 예시 : "<wnd app='"+str_AppName+"' />" => "<wnd app='{{str_AppName}}' />"
    - 조건 : (셀렉터 내 '.tostring','(',')' 미포함 시에만 작동)
```

Before | After 
|---|---|
&lt;html url | &lt;html app='msedge.exe' url
&lt;html html | &lt;html app='msedge.exe' html
&lt;html title | &lt;html app='msedge.exe' title
&lt;html idx | &lt;html app='msedge.exe' idx
&lt;html app='iexplore.exe' | &lt;html app='msedge.exe'
BrowserType="IE" | BrowserType="Edge"
BrowserType="{x:Null}" | BrowserType="Edge"
ProcessName="iexplorer"> | ProcessName="msedge">
ProcessName="iexplore"> | ProcessName="msedge">
ProcessName="iexplorer" /> | ProcessName="msedge" />
ProcessName="iexplore" /> | ProcessName="msedge" />
ProcessName="iexplorer"/> | ProcessName="msedge"/>
ProcessName="iexplore"/> | ProcessName="msedge"/>

**Comment by ParkWonBin** [comment]
## msedge 종료 후 세션 토큰 만료 관련
### 현상
서버에서 토큰 인증 기반 로그인 처리하는 시스템에 접속 시
 Kill Process "msedge" 로 프로세스를 종료하게 되면, 다음에 시스템을 열었을 때
"인증 토큰이 만료 되었습니다." 팝업이 뜨게 됩니다.

### 원인
사용자가 브라우저를 닫는 경우(close window - 닫기 버튼 클릭)
[닫기버튼]이 [로그인 중인 서버에 토큰 사용을 종료한다]는 시그널을 보내는 작업을 수행시키는 역할도 하나봅니다.
아마 해당 세션이 disytory 될 떄, 토큰 사용 종료도 함께 시키는 듯.

반면 process를 강제로 종료하는 경우(kill process - 작업관리자로 끄는 것과 동일)
작업 중인 시스템에서 잡고 있던 세션의 distroy 관련 프로세스가 정상동작 하지 않아, 
브라우저 종료 후 다시 해당 시스템으로 이동한 경우. [인증 토큰 만료]관련 이슈 생길 수 있습니다.

### 대처 
RPA 개발 시 Browser 종료 프로세스를 구현할 떄, Close Window를 권장합니다.
다면 1.해당 브라우저에서 다운로드 중인 파일이 있을 때, 2. IE Mode로 진입하여 IE 팝업이 뜰 때 등은
Close Window 이후에 직접 분기 처리를 해주어야 합니다. (그냥 창 닫기 버튼 누른 것과 동일하여, 팝업이 뜰 경우 닫히지 않음)

**Comment by ParkWonBin** [comment]
## IE -> Edge  IE Mode 관련

### 현상
가끔 ```<html app='msedge.exe'  />``` 로 하위 속성이 잡히지 않는 버그가 있다.
한 번 Indicate On Screen 하면 Validate 하나, 곧바로 다시 확인하면 inValidate로 표시됨.

### 원인 
UiPath Automation 19.10.1 기준. UiPath 에서 셀렉터를 찾을 때
명시되지 않은 속성에 대해 UiElement를 full search 하는 것이 아니라.
모종의 조건을 만족하는 UiElement만 인식하는 것 같다.
특정 Attribute를 명시하여 해결한다. 

### 대처
#### 1. IE 모드에서 IE Frame 내 요소를 인식하지 못하는 경우
``` xml
<wnd app='msedge.exe' cls='Chrome_WidgetWin_*' idx='*' />
<wnd cls='IEFrame' />
```
두번쨰 줄 ```<wnd cls='IEFrame' />``` 이 핵심인가봅니다. (누락 시 search 안함)

#### 2. foreground 상에 unique하게 떠있는 창을 인식하지 못하는 경우
``` xml
<wnd app='msedge.exe' cls='Chrome_WidgetWin_*' idx='*' />
```
idx='*'  를 명시해야 모든 full search 하나봅니다.
