### ISSUE TITLE
Batch 파일을 사용한 자동화 tip

### ISSUE THREAD

**Issue by ParkWonBin** [ParkWonBin/UIPath_study#9]
## Batch File, Powershell 사용 문법
- [x] bat, vb :  VB 코드 Compile [ ▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/9#issuecomment-1095175068)
- [x] bat, ps1 : 명령어 비교 [▶내용보기](https://github.com/ParkWonBin/UIPath_study/issues/9#issuecomment-1095107942)
- [x] bat, ps1 : 주석,선언,호출,출력,예시 [ ▶내용보기](https://github.com/ParkWonBin/UIPath_study/issues/9#issuecomment-1095113797)
- [x] PowerShell : 확장자 관련 [ ▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/9#issuecomment-1095088982)
- [x] PowerShell :  문법 관련[ ▶ 내용 보기](https://github.com/ParkWonBin/UIPath_study/issues/9#issuecomment-1095127554)

**Comment by ParkWonBin** [comment]
## 파일탐색기 단축키 [▶ 참고](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=toruin84&logNo=220555282969)  

### 폴더 이동 관련
| 단축키    | 설명                            |
| --------- | ------------------------------- |
| Win +E    | 파일탐색기 실행                 |
| Ctrl+F    | 파일검색(Ctrl+E 도 가능)        |
| F6        | 명령창 / 리본 / 파일탐색창 이동 |
| Alt+D     | 주소창 입력(Ctrl+L 도 가능)     |
| Alt+Up    | 상위 폴더로 이동                |
| Alt+Left  | 전 단계로 이동(Alt+Back도 가능) |
| Alt+Right | 앞 단계로 이동                  |
| Alt+Enter | 파일 속성보기                   |
| Shift+F10 | 마우스 우클릭과 동일            |

### 보기 창 관련
| 단축키       | 설명                      |
| ------------ | ------------------------- |
| F4           | 주소목록 보기             |
| F11          | 전체화면 보기             |
| Alt+P        | 미리보기 창 열기          |
| Alt+Shift+P  | 상세보기 창 열기          |
| Ctrl+Shift+N | 새폴더 만들기             |
| Shift+Del    | 휴지통 이동하지 않고 삭제 |

**Comment by ParkWonBin** [comment]
## 파워쉘 확장자 [▶ 참고](https://uzooin.tistory.com/237)
| 확장자         | 설명                            |
| :------------- | :------------------------------ |
| .ps1           | 파워셸 스크립트 파일            |
| .psm1          | 파워셸 스크립트 모듈            |
| .psd1          | 모듈 메니페스트                 |
| .psc           | 파워셸 콘솔 구성 파일           |
| .pscc          | 파워셸 세션 구성 파일           |
| .ps1xml        | 타입 확장을 포함한 기타 xml파일 |
| .format.ps1xml | 뷰 정의                         |

**Comment by ParkWonBin** [comment]
### BatchFile, Powershell 명령어 비교 [ ▶ 참고](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=nawoo&logNo=80138979222)
```yaml
bat, ps1 동일한 명령 :  
- cd : 작업 디렉토리 이동
- dir : 현재 작업 디렉토리 정보
- cls : 화면 초기화
- pause : 배치파일 수행 일시정지
- timeout : 일정 시간동안 배치파일 수행 정지
```
| - | BatchFile     | PowerShell   |
| :---: | ------------- | ------------ |
 | 확장자 | .bat | .ps1|
| 주석  | :: ,  rem     | #            |
| 선언  | set var=value | $var = value |
| 호출  | %var%         | $var         |
| 출력  | echo          | 그냥 입력    |
| 실행  | %파일명%      | .\$파일명    |

**Comment by ParkWonBin** [comment]
## BathFile 명령 예시
### 파일명 출력 [▶ bat 참고1](https://stackoverflow.com/questions/8797983/can-a-windows-batch-file-determine-its-own-file-name)
```bat
echo %0%      :: 전체경로
echo %~n0%    :: 파일이름만
echo %~n0%~x0 :: 파일이름과 확장자
echo %~nx0    :: 파일이름과 확장자
```
### 문자열 제어 [▶ bat 참고2](https://sysdocu.tistory.com/1516)
```bat
set var=0123456789     :: 변수 0123456789로 초기화
set var=               :: 변수 지우기
echo %var%             :: 변수 출력
echo %var:123=abc%     :: Replase| "123"을 "abc"로 바꿔 출력
echo %var:123=%        :: Replase| "123"을 지워서 출력
echo %var:~0%          :: Substring| 0번부터 출력
echo %var:~-5%         :: Substring|-5번부터 출력
echo %var:~0,2%        :: Substring| 0번부터 2개 출력
echo %var:~0,-2%       :: Substring| 0번부터-2번 직전까지 출력
echo %var:~-2,3%       :: Substring|-2번부터 3개 출력
```

### 시간지연[▶ bat 참고3](https://trustall.tistory.com/32)

```bat
set /p var=안내메시지
timeout /t %Seconds% /nobreak > NUL
::BatchFile 변수 할당시 "=" 좌우에 공백까지 변수명/값의 일부로 인식합니다.
```

**Comment by ParkWonBin** [comment]
## PowerShell 명령 관련
### SendKey [▶ 참고1](https://www.python2.net/questions-836160.htm)  [▶ 참고2](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=mjnms&logNo=220461858637)

```powershell
Start-Process -FilePath $FileName -WorkingDirectory $Path
$wsh = New-Object -ComObject Wscript.Shell 
$wsh.AppActivate("Window title of exe")
Start-Sleep 10 
$wsh.SendKeys("{TAB}") 
```
### Echo off [▶ 참고](https://www.python2.net/questions-763179.htm)
```powershell
$var = Read-Host -Prompt '안내메시지'
Start-Sleep $Seconds
function prompt {}
function prompt {
  $(if (Test-Path variable:/PSDebugContext) { '[DBG]: ' }
    else { '' }) + 'PS ' + $(Get-Location) +
      $(if ($NestedPromptLevel -ge 1) { '>>' }) + '> '
}
```

### Uipath Robot 실행 [▶ UiPath 문서](https://docs.uipath.com/robot/docs/arguments-description)
- Before Uipath Assistant (Uipath Studio <= 19.10)

```powershell
cls  # Clear Screen, 단축키 Ctrl+L 도 가능
$UiRobotPath = "" # 변수 선언
cd $UiRobotPath   # Change Directory
.\UiRobot.exe     # 현재 경로에서 파일 호출 ".\파일명"
Start-Sleep 10    # 10초 대기

# UiPath 19이하 버전에서 파일 실행 방법
$arg = "{'in_arrgument1' : '' , 'in_input':'' }"
.\UiRobot.exe execute  -file $xamlPath -input $arg
```

#### Run_PowerShell.bat
```bat 
::Run_PowerShell.bat
set filePath=%0%
set filePath=%filePath:~1,-4%ps1
:: "전체경로.bat" -> 전체경로.ps1
PowerShell.exe %filePath%
pause
```

### PowerShell UI Foreground Example
1. kill : 파일탐색기, UiPath.Studio
2. 파일탐색기 켜기($Directory)
3. 파일탐색기 포커스($Directory.split('\')[-1])
4. xmal 파일 검색(Ctrl+F, 파일명 입력)
5. 파일 선택(F6, down, enter)
```powershell
# Run_PowerShell.ps1
$killProcess = "explorer","UiPath.Studio"
foreach ($kilTarget in $killProcess)
{
    if( (get-Process | Where {$_.Name -eq $kilTarget} | measure).count -gt 0 )
    { Stop-Process -Name $kilTarget }
}

# Ui작업 - 파일탐색기
$workDir = "C:\Users\UserName\Documents\UiPath\BlankProcess"
$fileName = "main.xaml"
$selectorUiPath = "UiPath Studio"

$wsh = New-Object -ComObject Wscript.Shell 
$selectorDir = $workDir.split('\')[-1]

$wsh.Run("explorer.exe $workDir")
$wsh.AppActivate($selectorDir )
$wsh.SendKeys("^f")
$wsh.SendKeys($fileName) 
$wsh.SendKeys("{enter}") 
$wsh.SendKeys("{f6}") 
$wsh.SendKeys("{down}") 
$wsh.SendKeys("{enter}") 

$RetryNum = 0
do{
    $RetryNum++ 
    Start-Sleep 10
    $is_activate = $wsh.AppActivate($selectorUiPath)
    if ($is_activate)
    { $wsh.AppActivate($selectorUiPath) }
until ( ($is_activate) -or ($RetryNum -gt 6) )
```

**Comment by ParkWonBin** [comment]
### Run_Vb.bat [ ▶ 참고](https://stackoverflow.com/questions/8797983/can-a-windows-batch-file-determine-its-own-file-name)
```bat
:: [ README ] :::::::::::::
:: 사용법       : 실행시키고자 하는 VB파일의 경로를 targetPath에 등록합니다.
:: 주의사항1   : set 문장이 "=" 좌우에 공백문자가 들어가면 안됩니다. 
:: 주의사항2   : set 문장 마지막에 글자에 공백문자가 들어가면 안됩니다.
:: 주의사항3   : 경로를 입력할 때 따옴표 " 를 입력하면 안됩니다.
:: 주의사항4   : 변수 호출은 %변수명%으로 이루어지며, 문자열이 replace되어 명령으로 전달되는 느낌입니다.
:::::::::: [ Cmd 명령 구간 ]::::::::::::::
echo off
::: 같은 이름의 VB파일로 경로명 변경
set filePath=%0%
set filePath=%filePath:~1,-4%vb

::: Window에 기본적으로 내장된 VB Compiler 입력
set vbcCompiler=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\vbc.exe

::: VB Compiler로 script 실행
%vbcCompiler% %filePath%

::: VB Compiler가 만든 execute 파일 실행
%filePath:~0,-2%exe

::: Console.WriteLine 을 확인하기 위해 CMD창 멈춤
PAUSE 

:: echo %0%  : 전체경로
:: echo %~n0% : 파일이름만
:: echo %~n0%~x0 : 파일이름과 확장자
:: echo %~nx0   : 파일이름과 확장자
```

### Run_Vb.vb
```vb
'MainModule.vb
Module MainModule
    Public Sub Main()
'--------------------------------
        dim str_tmp as string
        str_tmp = "123"
        MsgBox("MsgBox(123) 입력 : " +str_tmp)
        Console.WriteLine("Console.WriteLine(""123"") 입력 : "+str_tmp)
'--------------------------------
    end Sub
end Module 
```
